### ISSUE TITLE
How to acces to upcoming releases ?

### ISSUE THREAD

**Issue by AugustinMauroy** [cutenode/nodevu#42]
In one of my projects I use `@nodevu/core` to get the nodeJS versions. But I couldn't find the latest version. (currently 21,22...).
Maybe someone has an idea of how to do it or you need to add a feature.

**Comment by AugustinMauroy** [comment]
👋 @bnb

**Comment by bnb** [comment]
@AugustinMauroy there's not a way - that data isn't available from official Node.js sources, and the way this module works is that it consumes and enhances those official Node.js sources. I don't think there's a future in which this feature is added, unfortunately.
